name: Run release

on:
  # Trigger a beta version release (pre-release) on push to the master branch.
  push:
    branches:
      - master
    tags-ignore:
      - "**" # Ignore all tags to prevent duplicate builds when tags are pushed.

  # Trigger a stable version release when a GitHub release is published.
  release:
    types: [published]

  # Allows manual workflow runs from GitHub's UI, with the ability to specify the type of release.
  workflow_dispatch:
    inputs:
      release_type:
        description: Release type
        required: true
        type: choice
        default: alpha
        options:
          - alpha
          - beta
          - final

jobs:
  run_code_checks:
    name: Run code checks
    uses: ./.github/workflows/run_code_checks.yaml

  # This job determines if the conditions are met for a release to occur. It will proceed if triggered manually,
  # for any published release, or if the commit on push does not begin with "docs" or "chore".
  should_release:
    name: Check whether to release
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'release' ||
      (
        github.event_name == 'push' &&
        !startsWith(github.event.head_commit.message, 'docs') &&
        !startsWith(github.event.head_commit.message, 'chore')
      )
    runs-on: ubuntu-latest
    steps:
      - name: Dummy step
        run: "true"

  update_changelog:
    name: Update changelog
    needs: [run_code_checks, should_release]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write # Required for OIDC authentication.
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up git
        run: |
          git config --global user.name "Apify Release Bot"
          git config --global user.email "noreply@apify.com"

      - name: Locally remove beta tags
        run: |
          git tags | grep 'b[0-9]' | xargs git tag --delete

      - name: Run git-cliff
        uses: orhun/git-cliff-action@v3
        with:
          config: cliff.toml
        env:
          OUTPUT: CHANGELOG.md

      - name: Commit and push the result
        run: |
          git commit -am "chore(release): Update changelog"
          git push origin master

  publish_to_pypi:
    name: Publish to PyPI
    needs: [run_code_checks, should_release]
    uses: ./.github/workflows/_publish_to_pypi.yaml

  # TODO: add job for publish package to Conda
  # https://github.com/apify/crawlee-py/issues/104
